## Create an IMPUTE formatted .info file as part of "conditional_analysis-GCTA.sh" as part of the conversion process from BGEN to MACH files. Note this is specific to working with UKB data

## Uses python 2.7.11 on Rescomp
## Run on long.qc 

import sys
import os
import pandas

snp_stat_file = sys.argv[1] # snp_stats file generated by qctool from UKB .bgen file
info_file = sys.argv[2] # output .info file

snp_data = pandas.read_table(snp_stat_file, delim_whitespace=True, comment="#")
info_data = pandas.DataFrame()
info_data["snp_id"] = snp_data.loc[:, "alternate_ids"]
info_data["rs_id"] = snp_data.loc[:, "rsid"]
info_data["position"] = snp_data.loc[:, "position"]
info_data["exp_freq_a1"] = snp_data.loc[:, "alleleA_frequency"]
info_data["info"] = snp_data.loc[:, "impute_info"]
info_data["certainty"] = "-9"
info_data["type"] = "-9"

info_data.to_csv(info_file, sep="\t", index=False)