## convert selected haplotypes generated by collate_haplotypes.py to lists of sample IDs

import sys

haplotype_file = sys.argv[1]
haplotype_id = sys.argv[2]
out_file = sys.argv[3]

sample_set = set()
with open(haplotype_file, "r") as hap_file:
	for line in hap_file:
		hap_id, haplotype = line.strip().split()
		if haplotype == haplotype_id:
			sample_id = hap_id.rsplit("_", 1)[0]
			sample_set.add(sample_id)

sample_list = list(sample_set)
with open(out_file, "w") as id_file:
	for sample in sorted(sample_list):
		id_file.write(sample + "\n")